
#
# Site title
title: "DSnML"
#

# A description of your site
description: "Hyde is a bold theme for the Jekyll blogging platform. Available for purchase at ThemeForest.net."

# The subpath of your site
# Leave baseurl blank when you run it in local
# baseurl: https://dsnml.github.io
# baseurl: https://dsnml.github.io

# In this theme static CSS is not used. 
sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://dsnml.com"

# Site navigation - list your url with text and the url (Path)
navigation:
- text: Home
  url: /
- text: Blog
  url: /blog/
- text: Archives
  url: /tags/

# Author Info
author_name: "DSnML"
author_bio: "Most interesting and curated content from the wonderful world of Data Science and Machine Learning"
author_url:  "http://dsnml.com"
author_image: author.jpg

# Social links
facebook_username: "username"
twitter_username: "username"
instagram_username: "username"


# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/pages/page:num/'
plugins: [jekyll-paginate]

